function [RippleHeight,RippleAspectRatio,RippleLength] = RippleGP(AREA,ShieldsParam,Shieldscritical,T,d50,OrbV,XMAX,YMAX)
%RippleGP Ripple prediction from Genetic Programming
%   This function imports the orbital velocity, Wave period, and the local d50 (for
%   ripples) and then spits out the appropriate ripple height, Length, and aspect ratio
%   accoridng to the eqns generated by Goldstein et al 2013.
%
%
%The MIT License (MIT)
%Copyright (c) 2016 Evan B. Goldstein
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Define some parameters
nu=0.000001; %  kinematic visc., m2/s
g=9.8;                      %gravity in m/s^2
SSD=1.65; %Submerged specific density (rhos/rho)-1
%T, Period in S
%d50 % size in mm

OrbitalVel=AREA.OrbitalVel;
REP=(d50/nu).*sqrt(g*d50*SSD);
AREA.REP=REP;
d=OrbitalVel*(T/pi);


RippleAspectRatio=AREA.RippleAspectRatio;
RippleLength=AREA.RippleLength;
RippleHeight=AREA.RippleHeight;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Ripples update only if shields parameter is greater than Shields Critical
for i=1:XMAX
    for j=1:YMAX
        if ShieldsParam(i,j)>Shieldscritical;
            %Length predictor 6
            RippleLength(i,j)=d(i,j)/(1.12+(d50(i,j)*2180));
            %Height predictor 5
            RippleHeight(i,j)=0.313*RippleLength(i,j)*(d50(i,j)*1000);
            RippleAspectRatio(i,j)=3.418/(22 + (RippleLength(i,j)/(1000*d50(i,j)))^2);
        end
    end
end
end
